### ISSUE TITLE
Select a range of numbers

### ISSUE THREAD

**Issue by spikelo** [ddosify/ddosify#107]
Hello everybody! Thank you for a very convenient and productive project! It would be great if you add an option:

`function (fake) Random input between (min, max int) int`

**Comment by kursataktas** [comment]
Hi @spikelo 

This would be a nice feature. But we have to find a convenient way to provide utility methods. Maybe we can add this support in a different way. For example, an integer array as an environment variable and a utility method to select a random value from it.

Proposal:

```
{
    "env": {
         "intArr": [1,5,4,3]
    },
    steps: [
        {
            "url": "https://example.com/{{random(intArr)}}"
        }
    ]
}
```

WDYT?

**Comment by kursataktas** [comment]
Hi @spikelo 

We have added the `rand()` utility method at [Ddosify v0.12.0](https://github.com/ddosify/ddosify/releases/tag/v0.12.0).
You can find a basic usage [here](https://github.com/ddosify/ddosify/tree/v0.12.0#hammer-overall-config-and-injection).
