### ISSUE TITLE
keep-alive connection between steps, but close it when the last step is reached. Open it again when requesting first step.

### ISSUE THREAD

**Issue by H25E** [ddosify/ddosify#118]
Hello,

In order to better simulate a user interaction with a web page I think it would be interesting to have this middle point for keep-alive in multi-step configurations. 

When a user interacts with a web page a number of URL are gathered and then the connection is closed when the user exits the web page or goes idle. So it would be nice to be able to simulate this behaviour, to keep alive the connection from the first step to the last one like a real user would do and then close it after the last step to simulate that a new different client it's connecting.

The idea is to generate a benchmarking load with the real ratio between connections / second and requests / second.

It's that possible right now? Would it be possible in the future?

**Comment by H25E** [comment]
Hi @fatihbaltaci, do you have a public roadmap?

**Comment by fatihbaltaci** [comment]
Hi @H25E, we don't have a public roadmap now but we will share our roadmap with the community in the future. Thanks.

**Comment by fatihbaltaci** [comment]
Hi @H25E, we introduced the `engine_mode` option in Ddosify release [v0.15.0](https://github.com/ddosify/ddosify/releases/tag/v0.15.0). You can set `engine_mode` to `distinct-user` for your use case. You can find the details in the [config file section](https://github.com/ddosify/ddosify#config-file). Thanks.
