### ISSUE TITLE
host header can not be modified (self_hosted)

### ISSUE THREAD

**Issue by EmilioMoreno** [ddosify/ddosify#218]
**Describe the bug**
using the Web UI I can add custom headers to any request. If I try to modify the host header either using a variable or using directly a static fqdn the test is run with the host header value set to the original ip / fqdn in the request

**To Reproduce**
Create a new test, with just one step, a simple get  and use a IP address in the url
In the step options, headers, add a host header with a name of any domain you want.
run the test in debug mode, the host header will show the IP address instead of the FQDN you set in the request.
**Expected behavior**
the request being sent with the value I set in the host header, whatever it is. No header should be excluded from modification.

**Screenshots**

**System (please complete the following information):**
 - OS: macOS ARM, docker desktop
 - Ddosify Version: self_hostest, docker

ddosify/selfhosted_hammer          1.4.0         
ddosify/selfhosted_frontend        1.1.2         
ddosify/selfhosted_backend         1.3.0         
ddosify/selfhosted_hammermanager   1.2.0         
chrislusf/seaweedfs                3.51          
influxdb                           2.6.1         
nginx                              1.23.3-alpine 
busybox                            1.34.1        
postgres                           13.6          
redis                              6.2.6         
rabbitmq                           3.9.4         

**Additional context**
Usage Case is as follows
In my environments all dns names are resolved to a central haproxy servers using the host header as routing criteria to different backend groups. The servers behind haproxy also validate the host header in the request before allow the request to be processed.

I am deploying a new set of servers with newer versions of the app and want to test them, but to isolate properly the servers from haproxy I need to set either the host header or create custom dns entries in the engine container.

**Comment by fatihbaltaci** [comment]
Hi @EmilioMoreno, thanks for raising this issue. We fixed it in the Ddosify `v1.0.5` release: https://github.com/ddosify/ddosify/releases/tag/v1.0.5

**Comment by fatihbaltaci** [comment]
Hello @EmilioMoreno, thank you for raising this issue. We fixed it and released the Ddosify Self Hosted Helm Chart `1.3.2`. You can easily upgrade your Ddosify Self-Hosted Helm to the latest version by referring to this documentation:

https://github.com/ddosify/ddosify-helm-charts#upgrading-the-ddosify-chart

If you need any assistance, please let me know.
