### ISSUE TITLE
Timeout greater than 30 seconds

### ISSUE THREAD

**Issue by FacuCastr0** [ddosify/ddosify#227]
Is there a way to set a request timeout greater than 30 seconds in the self-hosted application?
I'm testing a case where some requests take up to almost a minute and they get marked as failed.

**Comment by fatihbaltaci** [comment]
Hello @FacuCastr0, we increased the timeout value to `60` in the latest version of Ddosify Self-Hosted. Check: https://github.com/ddosify/ddosify/tree/master/selfhosted#%EF%B8%8F-quick-start-recommended
