### ISSUE TITLE
zsh: command not found: ddosify

### ISSUE THREAD

**Issue by ShivamJoker** [ddosify/ddosify#23]
I've installed ddosify via brew and go as well but still getting not found in path

**Comment by fatihbaltaci** [comment]
Hi @ShivamJoker, golang is not required to run ddosify. Did you add the homebrew binary packages path to `PATH` environment variable? 

For example:

```bash
export PATH="/opt/homebrew/bin:$PATH
```

**Comment by ShivamJoker** [comment]
It is already in the PATH and I tried running that command too still no effect

**Comment by fatihbaltaci** [comment]
Interesting. You can also use [this script](https://github.com/ddosify/ddosify#using-the-convenience-script-macos-and-linux) to install ddosify or manually download from the [releases page](https://github.com/ddosify/ddosify/releases/download/v0.5.1/ddosify_0.5.1_macos_all.tar.gz).

**Comment by ShivamJoker** [comment]
Okay this time the installation script worked. Although if would be good if brew can be fixed as well
