### ISSUE TITLE
Add an option to hide the progress showing only the result

### ISSUE THREAD

**Issue by bocharsky-bw** [ddosify/ddosify#57]
It would be cool to hide the progress output for every second and display only the RESULT putout at the end

**Comment by kursataktas** [comment]
Hi @bocharsky-bw 
Live output is helpful for terminating the test if something unintended happens during the test. On the other hand, ddosify has `stdout-json` output type which is not printing live results. It is developed for CI/CD purposes but it can also be used for instant tests. Output can be prettified by using [jq ](https://github.com/stedolan/jq). 

Still, I'm adding this to our roadmap. But there are more major feature requests, so we can't prioritize this for now.

**Comment by bocharsky-bw** [comment]
Thank you for the fast response! Yeah, `-o stdout-json` helped, thanks!

**Comment by kursataktas** [comment]
You are welcome!
