### ISSUE TITLE
Is there a way to supply randomized data

### ISSUE THREAD

**Issue by jonny7** [ddosify/ddosify#64]
Hi

Nice tool, I'm wondering if there is a way to send randomized data that follows a certain json definition? I see you have the config file, but i'm looking to send 1000s of request with generally unique bodies?

**Comment by kursataktas** [comment]
Hi,

We are working on the Parameterization feature. I'll update this issue once it's ready.

**Comment by gethari** [comment]
@jonny7 I'm looking for the same as well. @kursataktas Thanks for the update :) 

Really love this tool. Nicely done 👍

**Comment by kursataktas** [comment]
@gethari appreciate it!

There is an ongoing [PR](https://github.com/ddosify/ddosify/pull/45) if you would like to follow.

**Comment by kursataktas** [comment]
@gethari thanks!

There is an ongoing [PR](https://github.com/ddosify/ddosify/pull/45) if you would like to follow.

**Comment by kursataktas** [comment]
Hi @jonny7 and @gethari 

We released Ddosify v0.8.0. This version supports dynamic variables to generate random values. Here is the related section on readme:
https://github.com/ddosify/ddosify#parameterization-dynamic-variables

I'll close this issue in a few days if you don't face any issues.
