### ISSUE TITLE
Can't use it for localhost

### ISSUE THREAD

**Issue by Zerotask** [ddosify/ddosify#74]
I recently installed Ddosify as an extension for Docker Desktop (windows) and tried it with localhost.
I have a container up and running which can be accessed via port 80 and I can open it in the browser via http://localhost

When I do a load test, every single request fails:
![image](https://user-images.githubusercontent.com/20150243/176963420-53c9f771-cde3-4526-a222-9492ab296e91.png)
![image](https://user-images.githubusercontent.com/20150243/176963628-24352288-ba6a-409a-b89b-21b436520671.png)

Maybe I'm using it wrong, but I thought as a docker extension this is something I can use to test my local containers

**Comment by fatihbaltaci** [comment]
Hi @Zerotask, thanks for this issue. We changed the docker network type to host after this issue. 

We released an update for Ddosify Docker Extension with `0.1.0` version. It may take a while for Docker Desktop to fetch the update. Your problem will be solved with the new update.

Thanks.

**Comment by fatihbaltaci** [comment]
Hi @Zerotask, you can see the update in the Docker Desktop, if you face this problem again, please let me know.

**Comment by Zerotask** [comment]
I just updated the docker extension and it's working now. Thanks!
