### ISSUE TITLE
Docker extension fails with no error when selecting https and add https://example.com in host field.

### ISSUE THREAD

**Issue by jtorvald** [ddosify/ddosify#77]
I understand that the problem here is between the keyboard and the chair, but it's not super user friendly.
Better to strip https/http from the input or to give some message that it's not a valid domain.

**Comment by fatihbaltaci** [comment]
Hi @jtorvald, thanks for the issue. We'll give validation messages for the following release. 

I'll let you know when we update the extension.

Best

**Comment by fatihbaltaci** [comment]
Hi @jtorvald, we updated the Ddosify Docker Extension to `0.1.2`. You can update the extension on Docker Desktop. 

We show error messages on failure like this: 

![image](https://user-images.githubusercontent.com/10353650/185942390-8ebdc2fd-27dc-496a-8623-b50543e80b84.png)

Thanks
