### ISSUE TITLE
Docker extension Identify http client as ddosify

### ISSUE THREAD

**Issue by jtorvald** [ddosify/ddosify#78]
The logs now show a generic "Go-http-client/1.1" maybe better to show ddosify for Docker with the version or something

**Comment by fatihbaltaci** [comment]
Hi @jtorvald, We'll add a default `User-Agent` for the following Ddosify Docker extension release.

I'll let you know when we update the extension.

You can add the `User-Agent` header until we update the extension. 

![image](https://user-images.githubusercontent.com/10353650/185422318-5aacd66d-e884-435f-97d6-a2922bb5559a.png)

Best

**Comment by fatihbaltaci** [comment]
Hi @jtorvald, we updated the Ddosify Docker Extension to `0.1.2`. You can update the extension on Docker Desktop. 

We added a default `User-Agent` header for Ddosify Docker Extension with the version. 

![image](https://user-images.githubusercontent.com/10353650/185943383-4bf232b8-7673-411a-a4e1-ebb944504c4d.png)


Thanks

**Comment by danielcompton** [comment]
It seems like the Homebrew installed version still shows Go-http-client/1.1 as the user agent. Should this be set at the library level?
