### ISSUE TITLE
Is there support for mutual tls authentication?

### ISSUE THREAD

**Issue by tallinn1960** [ddosify/ddosify#82]
I can't find any options allowing ddosify to present a TLS client certificate to the server under test. Am I missing something or isn't that supported?

**Comment by fatihbaltaci** [comment]
Hi @tallinn1960, currently, there is no support for client certificates, but this is on our roadmap. I'll let you know when it's ready. 

Thanks.

**Comment by kursataktas** [comment]
Hi @tallinn1960 [Ddosify v0.9.0](https://github.com/ddosify/ddosify/releases/tag/v0.9.0) has this support thanks to great work by @zhiburt. If you face any issues, feel free to raise them.
