### ISSUE TITLE
Add interactive graphs to CLI

### ISSUE THREAD

**Issue by zhiburt** [ddosify/ddosify#84]
![image](https://user-images.githubusercontent.com/20165848/194538875-90882ba5-95d0-44d2-b8e7-a74af01bf005.png)

I think all of these could be done in a shell as well?
Using https://github.com/fdehau/tui-rs or something more simple to achieve the output just bar charts like htop.

I wonder if it's something which could be helpful.

**Comment by kursataktas** [comment]
It would be great but these type of (real-time) features dramatically reduces the performance of the tool. In Ddosify our primary focus is performance. Producing the maximum RPS as far as we can. According to our past experiments, real-time visualizing consumes more CPU than we expected.
