### ISSUE TITLE
Pass reference of a random id throughout steps

### ISSUE THREAD

**Issue by harshdalalcred** [ddosify/ddosify#90]
I want to have a simple config. 

Get a randomUUID from your function. 

Do a POST call with that randomUUID called rid1 as a step 1

Do a GET call with same randomUUID, rid1 as a step 2. 

This is currently not supported. 

--

TLDR: Supporting variables throughout the config scope.

**Comment by kursataktas** [comment]
Hi @harshdalalcred 

Looks similar to #46. I think we may cover this when we release the correlation feature. I'll update this thread once it is available.

**Comment by kursataktas** [comment]
Hi @harshdalalcred 

[Ddosify v0.11.0](https://github.com/ddosify/ddosify/releases/tag/v0.11.0) supports [correlation](https://github.com/ddosify/ddosify#correlation).  Please look at the [Scenario-Scoped Variables](https://github.com/ddosify/ddosify#scenario-scoped-variables) section to learn how to use the same random variable value throughout the scenario.
